<a href="https://colab.research.google.com/github/daroaa/MetNumUN2022II/blob/main/LAB2/daroa_LAB2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%matplotlib inline
!pip install -U fortran-magic
%reload_ext fortranmagic

import sys; sys.path.append('..')

import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

mpl.rc('figure', figsize=(12, 7))

ran_the_first_cell = True

jan2017 = pd.to_datetime(['2017-01-03 00:00:00+00:00',
 '2017-01-04 00:00:00+00:00',
 '2017-01-05 00:00:00+00:00',
 '2017-01-06 00:00:00+00:00',
 '2017-01-09 00:00:00+00:00',
 '2017-01-10 00:00:00+00:00',
 '2017-01-11 00:00:00+00:00',
 '2017-01-12 00:00:00+00:00',
 '2017-01-13 00:00:00+00:00',
 '2017-01-17 00:00:00+00:00',
 '2017-01-18 00:00:00+00:00',
 '2017-01-19 00:00:00+00:00',
 '2017-01-20 00:00:00+00:00',
 '2017-01-23 00:00:00+00:00',
 '2017-01-24 00:00:00+00:00',
 '2017-01-25 00:00:00+00:00',
 '2017-01-26 00:00:00+00:00',
 '2017-01-27 00:00:00+00:00',
 '2017-01-30 00:00:00+00:00',
 '2017-01-31 00:00:00+00:00',
 '2017-02-01 00:00:00+00:00'])
calendar = jan2017.values.astype('datetime64[D]')

event_dates = pd.to_datetime(['2017-01-06 00:00:00+00:00', 
                             '2017-01-07 00:00:00+00:00', 
                             '2017-01-08 00:00:00+00:00']).values.astype('datetime64[D]')
event_values = np.array([10, 15, 20])

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


/usr/local/lib/python3.7/dist-packages/fortranmagic.py:147: UserWarning: get_ipython_cache_dir has moved to the IPython.paths module since IPython 4.0.
  self._lib_dir = os.path.join(get_ipython_cache_dir(), 'fortran')


<center>
  <h1>The PyData Toolbox</h1>
  <h3>Scott Sanderson (Twitter: @scottbsanderson, GitHub: ssanderson)</h3>
  <h3><a href="https://github.com/ssanderson/pydata-toolbox">https://github.com/ssanderson/pydata-toolbox</a></h3>
</center>

# About Me:

<img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/me.jpg" alt="Drawing" style="width: 300px;"/>

- Senior Engineer at [Quantopian](www.quantopian.com)
- Background in Mathematics and Philosophy
- **Twitter:** [@scottbsanderson](https://twitter.com/scottbsanderson)
- **GitHub:** [ssanderson](github.com/ssanderson)

## Outline

- Built-in Data Structures
- Numpy `array`
- Pandas `Series`/`DataFrame`
- Plotting and "Real-World" Analyses

# Data Structures

> Rule 5. Data dominates. If you've chosen the right data structures and organized things well, the algorithms
will almost always be self-evident. Data structures, not algorithms, are central to programming.

- *Notes on Programming in C*, by Rob Pike.

# Lists

In [ ]:
assert ran_the_first_cell, "Oh noes!"

In [ ]:
l = [1, 'two', 3.0, 4, 5.0, "six"]
l

[1, 'two', 3.0, 4, 5.0, 'six']

**My own example 1**

In [ ]:
k = [6, 8, 20, "Four", 0]
k

[6, 8, 20, 'Four', 0]

In [ ]:
# Lists can be indexed like C-style arrays.
first = l[0]
second = l[1]
print("first:", first)
print("second:", second)

first: 1
second: two


**My own example 2**

In [ ]:
first = k[0]
third = k[2]
print ("First: ", first)
print ("Third: ", third)

First:  6
Third:  20


In [ ]:
# Negative indexing gives elements relative to the end of the list.
last = l[-1]
penultimate = l[-2]
print("last:", last)
print("second to last:", penultimate)

last: six
second to last: 5.0


**My own example 3**

In [ ]:
ultimo = k[-1]
penultimo = k[-2]
print ("último: ", ultimo)
print ("Penúltimo: ", penultimo)

último:  0
Penúltimo:  Four


In [ ]:
# Lists can also be sliced, which makes a copy of elements between 
# start (inclusive) and stop (exclusive)
sublist = l[1:3]
sublist

['two', 3.0]

**My own example 4**

In [ ]:
sublista = k[0:2]
sublista

[6, 8]

In [ ]:
# l[:N] is equivalent to l[0:N].
first_three = l[:3]
first_three

[1, 'two', 3.0]

**My own example 5**

In [ ]:
primeros_tres = k[:3]
primeros_tres

[6, 8, 20]

In [ ]:
# l[3:] is equivalent to l[3:len(l)].
after_three = l[3:]
after_three

[4, 5.0, 'six']

**My own example 6**

In [ ]:
despues_tres = k[3:]
despues_tres

['Four', 0]

In [ ]:
# There's also a third parameter, "step", which gets every Nth element.
l = ['a', 'b', 'c', 'd', 'e', 'f', 'g','h']
l[1:7:2]

['b', 'd', 'f']

**My own example 7**

In [ ]:
k = ['i', 'j', 'k', 'l', 'm', 'n', 'o']
k[0:4:1]

['i', 'j', 'k', 'l']

In [ ]:
# This is a cute way to reverse a list.
l[::-1]

['h', 'g', 'f', 'e', 'd', 'c', 'b', 'a']

**My own example 8**

In [ ]:
k[::-1]

['o', 'n', 'm', 'l', 'k', 'j', 'i']

In [ ]:
# Lists can be grown efficiently (in O(1) amortized time).
l = [1, 2, 3, 4, 5]
print("Before:", l)
l.append('six')
print("After:", l)

Before: [1, 2, 3, 4, 5]
After: [1, 2, 3, 4, 5, 'six']


**My own example 9**

In [ ]:
k = [7, 8, 9, 10, 11]
print("Antes: ",k)
k.append('Twelve')
print("Despues: ",k)

Antes:  [7, 8, 9, 10, 11]
Despues:  [7, 8, 9, 10, 11, 'Twelve']


In [ ]:
# Comprehensions let us perform elementwise computations.
l = [1, 2, 3, 4, 5]
[x * 2 for x in l]

[2, 4, 6, 8, 10]

**My own example 10**

In [ ]:
k = [7, 8, 9, 10, 11]
[x * 3 for x in k]

[21, 24, 27, 30, 33]

## Review: Python Lists

- Zero-indexed sequence of arbitrary Python values.
- Slicing syntax: `l[start:stop:step]` copies elements at regular intervals from `start` to `stop`.
- Efficient (`O(1)`) appends and removes from end.
- Comprehension syntax: `[f(x) for x in l if cond(x)]`.

# Dictionaries

In [ ]:
# Dictionaries are key-value mappings.
philosophers = {'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}
philosophers

{'David': 'Hume', 'Immanuel': 'Kant', 'Bertrand': 'Russell'}

**My own example 11**

In [ ]:
deportistas = {'Serena': 'Williams', 'Lionel':'Messi', 'Rafael':'Nadal', 'Usain':'Bolt'}
deportistas

{'Serena': 'Williams', 'Lionel': 'Messi', 'Rafael': 'Nadal', 'Usain': 'Bolt'}

In [ ]:
# Like lists, dictionaries are size-mutable.
philosophers['Ludwig'] = 'Wittgenstein'
philosophers

{'David': 'Hume',
 'Immanuel': 'Kant',
 'Bertrand': 'Russell',
 'Ludwig': 'Wittgenstein'}

**My own example 12**

In [ ]:
deportistas['Rigoberto'] = 'Uran'
deportistas

{'Serena': 'Williams',
 'Lionel': 'Messi',
 'Rafael': 'Nadal',
 'Usain': 'Bolt',
 'Rigoberto': 'Uran'}

In [ ]:
del philosophers['David']
philosophers

{'Immanuel': 'Kant', 'Bertrand': 'Russell', 'Ludwig': 'Wittgenstein'}

**My own example 13**

In [ ]:
del deportistas['Rafael']
deportistas

{'Serena': 'Williams', 'Lionel': 'Messi', 'Usain': 'Bolt', 'Rigoberto': 'Uran'}

In [ ]:
# No slicing.
philosophers['Bertrand':'Immanuel']

TypeError: ignored

## Review: Python Dictionaries

- Unordered key-value mapping from (almost) arbitrary keys to arbitrary values.
- Efficient (`O(1)`) lookup, insertion, and deletion.
- No slicing (would require a notion of order).

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pacino.gif" alt="Drawing" style="width: 100%;"/></center>


In [ ]:
# Suppose we have some matrices...
a = [[1, 2, 3],
     [2, 3, 4],
     [5, 6, 7],
     [1, 1, 1]]

b = [[1, 2, 3, 4],
     [2, 3, 4, 5]]

**My own example 14**

In [ ]:
c = [[0, 2, 4],
     [2, 5, 7],
     [4, 2, 1],
    ]
d = [[4, 6, 8, 1],
     [2, 5, 7, 9]]

In [ ]:
def matmul(A, B):
    """Multiply matrix A by matrix B."""
    rows_out = len(A)
    cols_out = len(B[0])
    out = [[0 for col in range(cols_out)] for row in range(rows_out)]
    
    for i in range(rows_out):
        for j in range(cols_out):
            for k in range(len(B)):
                out[i][j] += A[i][k] * B[k][j]
    return out

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/gross.gif" alt="Drawing" style="width: 50%;"/></center>


In [ ]:
%%time

matmul(a, b)

CPU times: user 41 µs, sys: 6 µs, total: 47 µs
Wall time: 51.7 µs


[[5, 8, 11, 14], [8, 13, 18, 23], [17, 28, 39, 50], [3, 5, 7, 9]]

**My own example 15**

In [ ]:
%%time

matmul(c,d)

CPU times: user 22 µs, sys: 0 ns, total: 22 µs
Wall time: 25 µs


[[4, 10, 14, 18], [18, 37, 51, 47], [20, 34, 46, 22]]

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 3)
randm

[[0.3489498886082003, 0.14848257529173758, 0.4103790645771902],
 [0.023815098124736145, 0.6991479894595979, 0.6912233131784211]]

**My own example 16**

In [ ]:
import random
def random_matrix(m, n):
    out = []
    for row in range(m):
        out.append([random.random() for _ in range(n)])
    return out

randm = random_matrix(2, 4)
randm

[[0.19820329094543399,
  0.8581131938802737,
  0.5070279421128552,
  0.9336706989297539],
 [0.47691475782846016,
  0.13152809171178903,
  0.5928787471388819,
  0.09138760212232266]]

In [ ]:
%%time
randa = random_matrix(600, 100)
randb = random_matrix(100, 600)
x = matmul(randa, randb)

CPU times: user 9.24 s, sys: 31.5 ms, total: 9.27 s
Wall time: 9.35 s


**My own example 17**

In [ ]:
%%time

randc = random_matrix(400, 200)
randd = random_matrix(200, 400)
z = matmul(randc,randd)

CPU times: user 8.12 s, sys: 34.1 ms, total: 8.16 s
Wall time: 8.19 s


In [ ]:
# Maybe that's not that bad?  Let's try a simpler case.
def python_dot_product(xs, ys):
    return sum(x * y for x, y in zip(xs, ys))

In [ ]:
%%fortran
subroutine fortran_dot_product(xs, ys, result)
    double precision, intent(in) :: xs(:)
    double precision, intent(in) :: ys(:)
    double precision, intent(out) :: result
    
    result = sum(xs * ys)
end

In [ ]:
list_data = [float(i) for i in range(100000)]
array_data = np.array(list_data)

**My own example 18**

In [ ]:
data_list = [float(i) for i in range(1000)]
data_arr = np.array(data_list)

In [ ]:
%%time
python_dot_product(list_data, list_data)

CPU times: user 11.4 ms, sys: 16 µs, total: 11.4 ms
Wall time: 11.5 ms


333328333350000.0

**My own example 19**

In [ ]:
%%time
python_dot_product(data_list, data_list)

CPU times: user 141 µs, sys: 0 ns, total: 141 µs
Wall time: 146 µs


332833500.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 181 µs, sys: 7 µs, total: 188 µs
Wall time: 198 µs


333328333350000.0

**My own example 20**

In [ ]:
%%time
fortran_dot_protduct(data_arr, data_arr)

NameError: ignored

**Numpy matrix multiplication**

In [ ]:
%%time
import numpy as np

m1 = np.array([[1,4,7],[2,5,8]])
m2 = np.array([[1,4],[2,5],[3,6]])
m3 = np.dot(m1,m2) 
print(m3) 

m1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
m2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 
m3 = np.dot(m1,m2) 
print(m3)

[[30 66]
 [36 81]]
[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]
CPU times: user 911 µs, sys: 6 µs, total: 917 µs
Wall time: 4.54 ms


**C matrix multiplication**

In [ ]:
%%writefile tmpc.c

#include<stdio.h>    
#include<stdlib.h>  
int main(){  
  int a[3][3],b[3][3],mul[10][10],r,c,i,j,k;      
  r=3;
  c=3;
  a[0][0]=1;
  a[0][1]=8;
  a[0][2]=5;
  a[1][0]=5;
  a[1][1]=2;
  a[1][2]=8;
  a[2][0]=7;
  a[2][1]=6;
  a[2][2]=4;

  b[0][0]=6;
  b[0][1]=7;
  b[0][2]=2;
  b[1][0]=1;
  b[1][1]=6;
  b[1][2]=7;
  b[2][0]=5;
  b[2][1]=3;
  b[2][2]=9;

  for(i=0;i<r;i++)    
  {    
    for(j=0;j<c;j++)    
    {    
      mul[i][j]=0;    
      for(k=0;k<c;k++)    
      {    
        mul[i][j]+=a[i][k]*b[k][j];    
      }    
    }    
  }    
    
  for(i=0;i<r;i++)    
  {    
    for(j=0;j<c;j++)    
    {    
      printf("%d\t",mul[i][j]);    
    }       
  printf("\n");    
  }    
  return 0;  
} 

Writing tmpc.c


In [ ]:
!gcc tmpc.c -o tmpc
!./tmpc

39	70	103	
72	71	96	
68	97	92	


**C++ matrix multiplication**

In [ ]:
%%writefile tmpcc.cc
#include <iostream>
using namespace std;

int main()
{
    int a[10][10], b[10][10], mult[10][10], r1, c1, r2, c2, i, j, k;
    r1=6;
    r2=6;
    c1=6;
    c2=6;

    for(i = 0; i < r1; ++i)
        for(j = 0; j < c1; ++j)
        {
            a[i][j]=3;
        }

    for(i = 0; i < r2; ++i)
        for(j = 0; j < c2; ++j)
        {
            b[i][j]=4;
        }

    for(i = 0; i < r1; ++i)
        for(j = 0; j < c2; ++j)
        {
            mult[i][j]=0;
        }

    for(i = 0; i < r1; ++i)
        for(j = 0; j < c2; ++j)
            for(k = 0; k < c1; ++k)
            {
                mult[i][j] += a[i][k] * b[k][j];
            }

    for(i = 0; i < r1; ++i)
    for(j = 0; j < c2; ++j)
    {
        cout << " " << mult[i][j];
        if(j == c2-1)
            cout << endl;
    }

    return 0;
}

Writing tmpcc.cc


In [ ]:
!g++ tmpcc.cc -o tmpcc
!./tmpcc

 72 72 72 72 72 72
 72 72 72 72 72 72
 72 72 72 72 72 72
 72 72 72 72 72 72
 72 72 72 72 72 72
 72 72 72 72 72 72


**Javascript matrix multiplication**

In [ ]:
%%writefile tmp.js

  
const N = 4;
  
function multiply(mat1, mat2, res)
{
    let i, j, k;
    for (i = 0; i < N; i++) {
        for (j = 0; j < N; j++) {
            res[i][j] = 0;
            for (k = 0; k < N; k++)
                res[i][j] += mat1[i][k] * mat2[k][j];
        }
    }
}
  
    let i, j;
      
    let res = new Array(N);
    for (let k = 0; k < N; k++)
        res[k] = new Array(N);
          
    let mat1 = [ [ 1, 1, 1, 1 ],
                       [ 2, 2, 2, 2 ],
                       [ 3, 3, 3, 3 ],
                       [ 4, 4, 4, 4 ] ];
  
    let mat2 = [ [ 1, 1, 1, 1 ],
                       [ 2, 2, 2, 2 ],
                       [ 3, 3, 3, 3 ],
                       [ 4, 4, 4, 4 ] ];
  
    multiply(mat1, mat2, res);
  
    console.log("Result matrix is <br>");
    for (i = 0; i < N; i++) {
        for (j = 0; j < N; j++)
            console.log(res[i][j] + " ");
        console.log("<br>");
    }
  


Writing tmp.js


In [ ]:
!node tmp.js

Result matrix is <br>
10 
10 
10 
10 
<br>
20 
20 
20 
20 
<br>
30 
30 
30 
30 
<br>
40 
40 
40 
40 
<br>


**Java matrix multiplication**

In [ ]:
%%writefile Main.java
class Main{  
  public static void main(String args[]){  
  
    int a[][]={{1,1,1},{2,2,2},{3,3,3}};    
    int b[][]={{1,1,1},{2,2,2},{3,3,3}};    
       
    int c[][]=new int[3][3];  //3 rows and 3 columns  
   
    for(int i=0;i<3;i++){    
      for(int j=0;j<3;j++){    
        c[i][j]=0;      
          for(int k=0;k<3;k++){      
            c[i][j]+=a[i][k]*b[k][j];      
          }
        System.out.print(c[i][j]+" ");
        }
      System.out.println();//new line    
    }    
  }
}

Writing Main.java


In [ ]:
!javac Main.java

In [ ]:
!java Main

6 6 6 
12 12 12 
18 18 18 


<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/sloth.gif" alt="Drawing" style="width: 1080px;"/></center>


## Why is the Python Version so Much Slower?

In [ ]:
# Dynamic typing.
def mul_elemwise(xs, ys):
    return [x * y for x, y in zip(xs, ys)]

mul_elemwise([1, 2, 3, 4], [1, 2 + 0j, 3.0, 'four'])
#[type(x) for x in _]

In [ ]:
# Interpretation overhead.
source_code = 'a + b * c'
bytecode = compile(source_code, '', 'eval')
import dis; dis.dis(bytecode)

  1           0 LOAD_NAME                0 (a)
              2 LOAD_NAME                1 (b)
              4 LOAD_NAME                2 (c)
              6 BINARY_MULTIPLY
              8 BINARY_ADD
             10 RETURN_VALUE


## Why is the Python Version so Slow?
- Dynamic typing means that every single operation requires dispatching on the input type.
- Having an interpreter means that every instruction is fetched and dispatched at runtime.
- Other overheads:
  - Arbitrary-size integers.
  - Reference-counted garbage collection.

> This is the paradox that we have to work with when we're doing scientific or numerically-intensive Python. What makes Python fast for development -- this high-level, interpreted, and dynamically-typed aspect of the language -- is exactly what makes it slow for code execution.

- Jake VanderPlas, [*Losing Your Loops: Fast Numerical Computing with NumPy*](https://www.youtube.com/watch?v=EEUXKG97YRw)

# What Do We Do?

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/runaway.gif" alt="Drawing" style="width: 50%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/thisisfine.gif" alt="Drawing" style="width: 1080px;"/></center>

- Python is slow for numerical computation because it performs dynamic dispatch on every operation we perform...

- ...but often, we just want to do the same thing over and over in a loop!

- If we don't need Python's dynamicism, we don't want to pay (much) for it.

- **Idea:** Dispatch **once per operation** instead of **once per element**.

In [ ]:
import numpy as np

data = np.array([1, 2, 3, 4])
data

array([1, 2, 3, 4])

**My own example 21**

In [ ]:
datos = np.array([5, 6, 7, 8])
datos

array([5, 6, 7, 8])

In [ ]:
data + data

array([2, 4, 6, 8])

**My own example 22**

In [ ]:
datos + datos

In [ ]:
%%time
# Naive dot product
(array_data * array_data).sum()

CPU times: user 0 ns, sys: 941 µs, total: 941 µs
Wall time: 957 µs


333328333350000.0

**My own example 23**

In [ ]:
%%time
(data_arr * data_arr).sum()

CPU times: user 1.15 ms, sys: 0 ns, total: 1.15 ms
Wall time: 998 µs


332833500.0

In [ ]:
%%time
# Built-in dot product.
array_data.dot(array_data)

CPU times: user 2.42 ms, sys: 5 ms, total: 7.42 ms
Wall time: 6.13 ms


333328333350000.0

**My own example 24**

In [ ]:
%%time
data_arr.dot(data_arr)

CPU times: user 578 µs, sys: 983 µs, total: 1.56 ms
Wall time: 1.4 ms


332833500.0

In [ ]:
%%time
fortran_dot_product(array_data, array_data)

CPU times: user 298 µs, sys: 0 ns, total: 298 µs
Wall time: 309 µs


333328333350000.0

**My own example 25**

In [ ]:
%%time
fortran_dot_product(data_arr, data_arr)

CPU times: user 10 µs, sys: 1e+03 ns, total: 11 µs
Wall time: 13.1 µs


332833500.0

In [ ]:
# Numpy won't allow us to write a string into an int array.
data[0] = "foo"

ValueError: ignored

In [ ]:
# We also can't grow an array once it's created.
data.append(3)

AttributeError: ignored

In [ ]:
# We **can** reshape an array though.
two_by_two = data.reshape(2, 2)
two_by_two

array([[1, 2],
       [3, 4]])

**My own example 26**

In [ ]:
dos_por_dos = datos.reshape(2,2)
dos_por_dos

array([[5, 6],
       [7, 8]])

Numpy arrays are:

- Fixed-type

- Size-immutable

- Multi-dimensional

- Fast\*

\* If you use them correctly.

# What's in an Array?

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6], dtype='int16').reshape(2, 3)
print("Array:\n", arr, sep='')
print("===========")
print("DType:", arr.dtype)
print("Shape:", arr.shape)
print("Strides:", arr.strides)
print("Data:", arr.data.tobytes())

Array:
[[1 2 3]
 [4 5 6]]
DType: int16
Shape: (2, 3)
Strides: (6, 2)
Data: b'\x01\x00\x02\x00\x03\x00\x04\x00\x05\x00\x06\x00'


# Core Operations

- Vectorized **ufuncs** for elementwise operations.
- Fancy indexing and masking for selection and filtering.
- Aggregations across axes.
- Broadcasting

# UFuncs

UFuncs (universal functions) are functions that operate elementwise on one or more arrays.

In [ ]:
data = np.arange(15).reshape(3, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

**My own example 27**

In [ ]:
datos = np.arange(18).reshape(3, 6)
datos

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
# Binary operators.
data * data

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196]])

**My own example 28**

In [ ]:
datos * datos

array([[  0,   1,   4,   9,  16,  25],
       [ 36,  49,  64,  81, 100, 121],
       [144, 169, 196, 225, 256, 289]])

In [ ]:
# Unary functions.
np.sqrt(data)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

**My own example 29**

In [ ]:
np.sqrt(datos)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563]])

In [ ]:
# Comparison operations
(data % 3) == 0

array([[ True, False, False,  True, False],
       [False,  True, False, False,  True],
       [False, False,  True, False, False]])

**My own example 30**

In [ ]:
(datos%2) == 0

array([[ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False],
       [ True, False,  True, False,  True, False]])

In [ ]:
# Boolean combinators.
((data % 2) == 0) & ((data % 3) == 0)

array([[ True, False, False, False, False],
       [False,  True, False, False, False],
       [False, False,  True, False, False]])

**My own example 31**

In [ ]:
((datos%3) !=0) & ((datos%2) ==0)

array([[False, False,  True, False,  True, False],
       [False, False,  True, False,  True, False],
       [False, False,  True, False,  True, False]])

In [ ]:
# as of python 3.5, @ is matrix-multiply
data @ data.T

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

**My own example 32**

In [ ]:
datos @datos.T

array([[  55,  145,  235],
       [ 145,  451,  757],
       [ 235,  757, 1279]])

# UFuncs Review

- UFuncs provide efficient elementwise operations applied across one or more arrays.
- Arithmetic Operators (`+`, `*`, `/`)
- Comparisons (`==`, `>`, `!=`)
- Boolean Operators (`&`, `|`, `^`)
- Trigonometric Functions (`sin`, `cos`)
- Transcendental Functions (`exp`, `log`)

# Selections

We often want to perform an operation on just a subset of our data.

In [ ]:
sines = np.sin(np.linspace(0, 3.14, 10))
cosines = np.cos(np.linspace(0, 3.14, 10))
sines

array([0.        , 0.34185385, 0.64251645, 0.86575984, 0.98468459,
       0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 33**

In [ ]:
sin = np.sin(np.linspace(0, 3.14, 9))
cosin = np.cos(np.linspace(0, 3.14, 9))
sin

array([0.        , 0.3824995 , 0.70682518, 0.92365081, 0.99999968,
       0.92426   , 0.70795091, 0.38397055, 0.00159265])

In [ ]:
# Slicing works with the same semantics as Python lists.
sines[0]

0.0

**My own example 34**

In [ ]:
sin[1]

0.3824994972760097

In [ ]:
sines[:3]  # First three elements  

array([0.        , 0.34185385, 0.64251645])

**My own example 35**

In [ ]:
#Primeros cuatro elementos
sin[:4]

array([0.        , 0.3824995 , 0.70682518, 0.92365081])

In [ ]:
sines[5:]  # Elements from 5 on.

array([0.98496101, 0.8665558 , 0.64373604, 0.34335012, 0.00159265])

**My own example 36**

In [ ]:
#Elementos desde la posición 3 en adelante
sin[3:]

array([0.92365081, 0.99999968, 0.92426   , 0.70795091, 0.38397055,
       0.00159265])

In [ ]:
sines[::2]  # Every other element.

array([0.        , 0.64251645, 0.98468459, 0.8665558 , 0.34335012])

**My own example 37**

In [ ]:
sin[::2]

array([0.        , 0.70682518, 0.99999968, 0.70795091, 0.00159265])

In [ ]:
# More interesting: we can index with boolean arrays to filter by a predicate.
print("sines:\n", sines)
print("sines > 0.5:\n", sines > 0.5)
print("sines[sines > 0.5]:\n", sines[sines > 0.5])

sines:
 [0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]
sines > 0.5:
 [False False  True  True  True  True  True  True False False]
sines[sines > 0.5]:
 [0.64251645 0.86575984 0.98468459 0.98496101 0.8665558  0.64373604]


In [ ]:
# We index with lists/arrays of integers to select values at those indices.
print(sines)
sines[[0, 4, 7]]

[0.         0.34185385 0.64251645 0.86575984 0.98468459 0.98496101
 0.8665558  0.64373604 0.34335012 0.00159265]


array([0.        , 0.98468459, 0.64373604])

**My own example 38**

In [ ]:
print(sin)
sin[[0, 2, 4]]

[0.         0.3824995  0.70682518 0.92365081 0.99999968 0.92426
 0.70795091 0.38397055 0.00159265]


array([0.        , 0.70682518, 0.99999968])

In [ ]:
# Index arrays are often used for sorting one or more arrays.
unsorted_data = np.array([1, 3, 2, 12, -1, 5, 2])

**My own example 39**

In [ ]:
data_un = np.array([-1, 3, 6, -5, 8])

In [ ]:
sort_indices = np.argsort(unsorted_data)
sort_indices

array([4, 0, 2, 6, 1, 5, 3])

**My own example 40**

In [ ]:
sort_ind = np.argsort(data_un)
sort_ind

array([3, 0, 1, 2, 4])

In [ ]:
unsorted_data[sort_indices]

array([-1,  1,  2,  2,  3,  5, 12])

**My own example 41**

In [ ]:
data_un[sort_ind]

array([-5, -1,  3,  6,  8])

In [ ]:
market_caps = np.array([12, 6, 10, 5, 6])  # Presumably in dollars?
assets = np.array(['A', 'B', 'C', 'D', 'E'])

**My own example 42**

In [ ]:
cap_mar = np.array([4, 7, 6, 2])
activos = np.array(['G', 'O', 'U', 'M'])

In [ ]:
# Sort assets by market cap by using the permutation that would sort market caps on ``assets``.
sort_by_mcap = np.argsort(market_caps)
assets[sort_by_mcap]

array(['D', 'B', 'E', 'C', 'A'], dtype='<U1')

**My own example 43**

In [ ]:
cap_sort = np.argsort(cap_mar)
activos[cap_sort]

array(['M', 'G', 'U', 'O'], dtype='<U1')

In [ ]:
# Indexers are also useful for aligning data.
print("Dates:\n", repr(event_dates))
print("Values:\n", repr(event_values))
print("Calendar:\n", repr(calendar))

Dates:
 array(['2017-01-06', '2017-01-07', '2017-01-08'], dtype='datetime64[D]')
Values:
 array([10, 15, 20])
Calendar:
 array(['2017-01-03', '2017-01-04', '2017-01-05', '2017-01-06',
       '2017-01-09', '2017-01-10', '2017-01-11', '2017-01-12',
       '2017-01-13', '2017-01-17', '2017-01-18', '2017-01-19',
       '2017-01-20', '2017-01-23', '2017-01-24', '2017-01-25',
       '2017-01-26', '2017-01-27', '2017-01-30', '2017-01-31',
       '2017-02-01'], dtype='datetime64[D]')


In [ ]:
print("Raw Dates:", event_dates)
print("Indices:", calendar.searchsorted(event_dates))
print("Forward-Filled Dates:", calendar[calendar.searchsorted(event_dates)])

Raw Dates: ['2017-01-06' '2017-01-07' '2017-01-08']
Indices: [3 4 4]
Forward-Filled Dates: ['2017-01-06' '2017-01-09' '2017-01-09']


On multi-dimensional arrays, we can slice along each axis independently.

In [ ]:
data = np.arange(25).reshape(5, 5)
data

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**My own example 44**

In [ ]:
datos = np.arange(16).reshape(4, 4)
datos

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
data[:2, :2]  # First two rows and first two columns.

array([[0, 1],
       [5, 6]])

**My own example 45**



In [ ]:
#primera fila y primera columna
datos[:1, :1]

array([[0]])

In [ ]:
data[:2, [0, -1]]  # First two rows, first and last columns.

array([[0, 4],
       [5, 9]])

**My own example 46**

In [ ]:
datos[:3, [0,-2]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [ ]:
data[(data[:, 0] % 2) == 0]  # Rows where the first column is divisible by two.

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

**My own example 47**

In [ ]:
datos[(datos[:, 1] % 3) == 0]

array([[ 8,  9, 10, 11]])

# Selections Review

- Indexing with an integer removes a dimension.
- Slicing operations work on Numpy arrays the same way they do on lists.
- Indexing with a boolean array filters to True locations.
- Indexing with an integer array selects indices along an axis.
- Multidimensional arrays can apply selections independently along different axes.

## Reductions

Functions that reduce an array to a scalar.

$Var(X) = \frac{1}{N}\sqrt{\sum_{i=1}^N (x_i - \bar{x})^2}$

In [ ]:
def variance(x):
    return ((x - x.mean()) ** 2).sum() / len(x)

In [ ]:
variance(np.random.standard_normal(1000))

0.9939087302261455

**My own example 48**

In [ ]:
variance(np.random.standard_normal(100))

1.1121472120345066

- `sum()` and `mean()` are both **reductions**.

- In the simplest case, we use these to reduce an entire array into a single value...

In [ ]:
data = np.arange(30)
data.mean()

14.5

**My own example 49**

In [ ]:
datos = np.arange(28)
datos.mean()

13.5

- ...but we can do more interesting things with multi-dimensional arrays.

In [ ]:
data = np.arange(30).reshape(3, 10)
data

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

**My own example 50**

In [ ]:
datos = np.arange(24).reshape(4,6)

In [ ]:
data.mean()

14.5

**My own example 51**

In [ ]:
datos.mean()

11.5

In [ ]:
data.mean(axis=0)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

**My own example 52**

In [ ]:
datos.mean(axis=0)

array([ 9., 10., 11., 12., 13., 14.])

In [ ]:
data.mean(axis=1)

array([ 4.5, 14.5, 24.5])

**My own example 53**

In [ ]:
datos.mean(axis=1)

array([ 2.5,  8.5, 14.5, 20.5])

## Reductions Review

- Reductions allow us to perform efficient aggregations over arrays.
- We can do aggregations over a single axis to collapse a single dimension.
- Many built-in reductions (`mean`, `sum`, `min`, `max`, `median`, ...).

# Broadcasting

In [ ]:
row = np.array([1, 2, 3, 4])
column = np.array([[1], [2], [3]])
print("Row:\n", row, sep='')
print("Column:\n", column, sep='')

Row:
[1 2 3 4]
Column:
[[1]
 [2]
 [3]]


**My own example 54**

In [ ]:
fila = np.array([2, 4, 6, 8])
columna = np.array([[1],[3],[5]])
print("Fila:\n", fila, sep='')
print("Columna:\n", columna, sep='')

Fila:
[2 4 6 8]
Columna:
[[1]
 [3]
 [5]]


In [ ]:
row + column

array([[2, 3, 4, 5],
       [3, 4, 5, 6],
       [4, 5, 6, 7]])

**My own example 55**

In [ ]:
fila + columna

array([[ 3,  5,  7,  9],
       [ 5,  7,  9, 11],
       [ 7,  9, 11, 13]])

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/broadcasting.png" alt="Drawing" style="width: 60%;"/></center>

<h5>Source: http://www.scipy-lectures.org/_images/numpy_broadcasting.png</h5>

In [ ]:
# Broadcasting is particularly useful in conjunction with reductions.
print("Data:\n", data, sep='')
print("Mean:\n", data.mean(axis=0), sep='')
print("Data - Mean:\n", data - data.mean(axis=0), sep='')

Data:
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]
Mean:
[10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]
Data - Mean:
[[-10. -10. -10. -10. -10. -10. -10. -10. -10. -10.]
 [  0.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [ 10.  10.  10.  10.  10.  10.  10.  10.  10.  10.]]


# Broadcasting Review

- Numpy operations can work on arrays of different dimensions as long as the arrays' shapes are still "compatible".
- Broadcasting works by "tiling" the smaller array along the missing dimension.
- The result of a broadcasted operation is always at least as large in each dimension as the largest array in that dimension.

# Numpy Review

- Numerical algorithms are slow in pure Python because the overhead dynamic dispatch dominates our runtime.

- Numpy solves this problem by:
  1. Imposing additional restrictions on the contents of arrays.
  2. Moving the inner loops of our algorithms into compiled C code.

- Using Numpy effectively often requires reworking an algorithms to use vectorized operations instead of for-loops, but the resulting operations are usually simpler, clearer, and faster than the pure Python equivalent.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/unicorn.jpg" alt="Drawing" style="width: 75%;"/></center>

Numpy is great for many things, but...

- Sometimes our data is equipped with a natural set of **labels**:
  - Dates/Times
  - Stock Tickers
  - Field Names (e.g. Open/High/Low/Close)

- Sometimes we have **more than one type of data** that we want to keep grouped together.
  - Tables with a mix of real-valued and categorical data.

- Sometimes we have **missing** data, which we need to ignore, fill, or otherwise work around.

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/panda-wrangling.gif" alt="Drawing" style="width: 75%;"/></center>

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/pandas_logo.png" alt="Drawing" style="width: 75%;"/></center>


Pandas extends Numpy with more complex data structures:

- `Series`: 1-dimensional, homogenously-typed, labelled array.
- `DataFrame`: 2-dimensional, semi-homogenous, labelled table.

Pandas also provides many utilities for: 
- Input/Output
- Data Cleaning
- Rolling Algorithms
- Plotting

# Selection in Pandas

In [ ]:
s = pd.Series(index=['a', 'b', 'c', 'd', 'e'], data=[1, 2, 3, 4, 5])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

**My own example 56**

In [ ]:
d = pd.Series(index=['a','e','i','o','u'], data = [1,2, 3, 4, 5])

In [ ]:
# There are two pieces to a Series: the index and the values.
print("The index is:", s.index)
print("The values are:", s.values)

The index is: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
The values are: [1 2 3 4 5]


**My own example 57**

In [ ]:
print("The index is:", d.index)
print("The values are:", d.values)

The index is: Index(['a', 'e', 'i', 'o', 'u'], dtype='object')
The values are: [1 2 3 4 5]


In [ ]:
# We can look up values out of a Series by position...
s.iloc[0]

1

**My own example 58**

In [ ]:
d.iloc[1]

2

In [ ]:
# ... or by label.
s.loc['a']

1

**My own example 59**

In [ ]:
d.loc['i']

3

In [ ]:
# Slicing works as expected...
s.iloc[:2]

a    1
b    2
dtype: int64

**My own example 60**

In [ ]:
d.iloc[:3]

a    1
e    2
i    3
dtype: int64

In [ ]:
# ...but it works with labels too!
s.loc[:'c']

a    1
b    2
c    3
dtype: int64

**My own example 61**

In [ ]:
d.loc[:'o']

a    1
e    2
i    3
o    4
dtype: int64

In [ ]:
# Fancy indexing works the same as in numpy.
s.iloc[[0, -1]]

a    1
e    5
dtype: int64

**My own example 62**

In [ ]:
d.iloc[[2, -1]]

i    3
u    5
dtype: int64

In [ ]:
# As does boolean masking.
s.loc[s > 2]

c    3
d    4
e    5
dtype: int64

**My own example 63**

In [ ]:
d.loc[d<4]

a    1
e    2
i    3
dtype: int64

In [ ]:
# Element-wise operations are aligned by index.
other_s = pd.Series({'a': 10.0, 'c': 20.0, 'd': 30.0, 'z': 40.0})
other_s

a    10.0
c    20.0
d    30.0
z    40.0
dtype: float64

**My own example 64**

In [ ]:
other_d = pd.Series({'a': 10.0, 'e': 20.0, 'i': 30.0, 'o': 40.0, 'u':50.0})
other_d

a    10.0
e    20.0
i    30.0
o    40.0
u    50.0
dtype: float64

In [ ]:
s + other_s

a    11.0
b     NaN
c    23.0
d    34.0
e     NaN
z     NaN
dtype: float64

**My own example 65**

In [ ]:
d + other_d

a    11.0
e    22.0
i    33.0
o    44.0
u    55.0
dtype: float64

In [ ]:
# We can fill in missing values with fillna().
(s + other_s).fillna(0.0)

a    11.0
b     0.0
c    23.0
d    34.0
e     0.0
z     0.0
dtype: float64

**My own example 66**

In [ ]:
(d + other_d).fillna(0.0)

a    11.0
e    22.0
i    33.0
o    44.0
u    55.0
dtype: float64

In [ ]:
# Most real datasets are read in from an external file format.
aapl = pd.read_csv('AAPL.csv', parse_dates=['Date'], index_col='Date')
aapl.head()

FileNotFoundError: ignored

In [ ]:
# Slicing generalizes to two dimensions as you'd expect:
aapl.iloc[:2, :2]

NameError: ignored

In [ ]:
aapl.loc[pd.Timestamp('2010-02-01'):pd.Timestamp('2010-02-04'), ['Close', 'Volume']]

# Rolling Operations

<center><img src="https://raw.githubusercontent.com/ssanderson/pydata-toolbox/master/notebooks/images/rolling.gif" alt="Drawing" style="width: 75%;"/></center>

In [ ]:
aapl.rolling(5)[['Close', 'Adj Close']].mean().plot();

NameError: ignored

In [ ]:
# Drop `Volume`, since it's way bigger than everything else.
aapl.drop('Volume', axis=1).resample('2W').max().plot();

In [ ]:
# 30-day rolling exponentially-weighted stddev of returns.
aapl['Close'].pct_change().ewm(span=30).std().plot();

# "Real World" Data

In [ ]:
!githubdl -u https://github.com/ssanderson/pydata-toolbox -d demos -g 0260ccdcf10212d2a8f1d9ff6fbc7e55b00a4ad2

In [ ]:
from demos.avocados import read_avocadata

avocados = read_avocadata('2014', '2016')
avocados.head()

In [ ]:
# Unlike numpy arrays, pandas DataFrames can have a different dtype for each column.
avocados.dtypes

In [ ]:
# What's the regional average price of a HASS avocado every day?
hass = avocados[avocados.Variety == 'HASS']
hass.groupby(['Date', 'Region'])['Weighted Avg Price'].mean().unstack().ffill().plot();

In [ ]:
def _organic_spread(group):

    if len(group.columns) != 2:
        return pd.Series(index=group.index, data=0.0)
    
    is_organic = group.columns.get_level_values('Organic').values.astype(bool)
    organics = group.loc[:, is_organic].squeeze()
    non_organics = group.loc[:, ~is_organic].squeeze()
    diff = organics - non_organics
    return diff

def organic_spread_by_region(df):
    """What's the difference between the price of an organic 
    and non-organic avocado within each region?
    """
    return (
        df
        .set_index(['Date', 'Region', 'Organic'])
         ['Weighted Avg Price']
        .unstack(level=['Region', 'Organic'])
        .ffill()
        .groupby(level='Region', axis=1)
        .apply(_organic_spread)
    )

In [ ]:
organic_spread_by_region(hass).plot();
plt.gca().set_title("Daily Regional Organic Spread");
plt.legend(bbox_to_anchor=(1, 1));

In [ ]:
spread_correlation = organic_spread_by_region(hass).corr()
spread_correlation

In [ ]:
import seaborn as sns
grid = sns.clustermap(spread_correlation, annot=True)
fig = grid.fig
axes = fig.axes
ax = axes[2]
ax.set_xticklabels(ax.get_xticklabels(), rotation=45);

# Pandas Review

- Pandas extends numpy with more complex datastructures and algorithms.
- If you understand numpy, you understand 90% of pandas.
- `groupby`, `set_index`, and `unstack` are powerful tools for working with categorical data.
- Avocado prices are surprisingly interesting :)

#Avocados thing

In [ ]:
from io import BytesIO
import os
from urllib.parse import urlencode

import requests
import numpy as np
import pandas as pd


def read_avocadata(start_date, end_date, cache_loc='avocadata.html'):
    """Download avocado data to a dataframe.
    Parameters
    ----------
    """
    start_date = pd.Timestamp(start_date)
    end_date = pd.Timestamp(end_date)
    base_url = 'https://www.marketnews.usda.gov/mnp/fv-report-retail'
    query_params = {
        'class': ['FRUITS'],
        'commodity': ['AVOCADOS'],
        'compareLy': ['No'],
        'endDate': [end_date.strftime("%m/%d/%Y")],
        'format': ['excel'],
        'organic': ['ALL'],
        'portal': ['fv'],
        'region': ['ALL'],
        'repDate': [start_date.strftime("%m/%d/%Y")],
        'type': ['retail'],
    }

    url = base_url + '?' + urlencode(query_params, doseq=1)

    if not os.path.exists(cache_loc):
        resp = requests.get(url, stream=True)
        resp.raise_for_status()

        with open(cache_loc, 'wb') as f:
            for block in resp.iter_content(chunk_size=4096):
                f.write(block)
        f.close()

    with open(cache_loc, 'rb') as f:
        frame = pd.read_html(f, header=0)[0]

    # Cleanup
    frame = frame[frame['Unit'] == 'each']
    frame['Organic'] = (frame['Organic'] == 'Y')
    frame['Variety'].replace(
        {'VARIOUS GREENSKIN VARIETIES': 'GREENSKIN'},
        inplace=True,
    )
    frame['Date'] = pd.to_datetime(frame['Date'].values, utc=True)

    frame['Region'] = frame['Region'].str.replace(' U.S.', '')
    frame['Region'] = frame['Region'].str.replace(' ', '_')

    # Drop useless columns.
    return frame.drop(
        ['Class', 'Commodity', 'Environment', 'Unit', '% Marked Local'],
        axis=1,
    )

In [ ]:
## Needed Libraries.
from urllib.parse import urlencode 
import pandas as pd

import requests

## In this case, we will obtain TOMATOES data.
base_url = 'https://www.marketnews.usda.gov/mnp/fv-report-retail'
query_params = {
  'class': ['VEGETABLES'], ## Change Fruit with Vegetables
  'commodity': ['TOMATOES'], ## Change Avocados with Tomatoes
  'compareLy': ['No'],
  'endDate': ['01/01/2021'], ## Hardcoding end Date
  'repDate': ['01/01/2020'], ## Hardcoding rep Date
  'format': ['excel'],
  'organic': ['ALL'],
  'portal': ['fv'],
  'region': ['ALL'],
  'type': ['retail'],
}

## Build URL to send request.
url = base_url + '?' + urlencode(query_params, doseq=1)

## Request data from url
resp = requests.get(url, stream=True)

## Create File with data.
with open('data.html', 'wb') as f:
            for block in resp.iter_content(chunk_size=4096):
                f.write(block)
            f.close()

## Read data from file.
tomatoes_data = pd.read_html('data.html', header=0)[0] 



In [ ]:
tomatoes_data

Date          Region       Class Commodity  \
0     01/03/2020        NATIONAL  VEGETABLES  TOMATOES   
1     01/03/2020        NATIONAL  VEGETABLES  TOMATOES   
2     01/03/2020        NATIONAL  VEGETABLES  TOMATOES   
3     01/03/2020        NATIONAL  VEGETABLES  TOMATOES   
4     01/03/2020        NATIONAL  VEGETABLES  TOMATOES   
...          ...             ...         ...       ...   
1918  01/01/2021  NORTHWEST U.S.  VEGETABLES  TOMATOES   
1919  01/01/2021  NORTHWEST U.S.  VEGETABLES  TOMATOES   
1920  01/01/2021          HAWAII  VEGETABLES  TOMATOES   
1921  01/01/2021          ALASKA  VEGETABLES  TOMATOES   
1922  01/01/2021          HAWAII  VEGETABLES  TOMATOES   

                             Variety Organic Environment       Unit  \
0                                NaN     NaN         NaN  per pound   
1     VINE RIPE - HEIRLOOM VARIETIES     NaN         NaN  per pound   
2     VINE RIPE - HEIRLOOM VARIETIES       Y         NaN  per pound   
3                         VINE RIPES     NaN         NaN  per pound   
4                         VINE RIPES       Y  Greenhouse  per pound   
...                              ...     ...         ...        ...   
1918                      VINE RIPES     NaN  Greenhouse  per pound   
1919         VINE RIPES, ON THE VINE     NaN  Greenhouse  per pound   
1920                             NaN     NaN         NaN  per pound   
1921         VINE RIPES, ON THE VINE     NaN  Greenhouse  per pound   
1922         VINE RIPES, ON THE VINE     NaN  Greenhouse  per pound   

      Number of Stores  Weighted Avg Price  Low Price  High Price  \
0                  212                1.81        NaN         NaN   
1                   46                3.34        NaN         NaN   
2                   23                3.99        NaN         NaN   
3                 2255                1.66        NaN         NaN   
4                  245                1.48        NaN         NaN   
...                ...                 ...        ...         ...   
1918                10                2.49       2.49        2.49   
1919               250                1.92       1.49        1.99   
1920                 4                2.29       2.29        2.29   
1921                34                2.49       2.39        2.49   
1922                26                2.64       2.29        2.69   

      % Marked Local  
0                NaN  
1                NaN  
2                NaN  
3                NaN  
4                NaN  
...              ...  
1918             NaN  
1919             NaN  
1920             NaN  
1921             NaN  
1922             NaN  

[1923 rows x 13 columns]

# Thanks!